GET http://localhost:3000/

###
GET http://localhost:3000/post/67487f24e9a8933548f3ddc2

###
POST http://localhost:3000/
Content-Type: application/json

{
    "owner": "KimK",
    "title": "The Best Post",
    "content": "This is my first post"
}